### ISSUE TITLE
Uncaught TypeError: Cannot read property 'save' of undefined

### ISSUE THREAD

**Issue by uebergeek999** [ndr-brt/atom-p5js#1]
Steps to reproduce:  Packages menu->atom-p5.js->Toggle.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-p5js](https://github.com/ndr-brt/atom-p5js) package 0.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'save' of undefined

```
At /Users/amy/.atom/packages/atom-p5js/lib/atom-p5js.js:72

TypeError: Cannot read property 'save' of undefined
    at /packages/atom-p5js/lib/atom-p5js.js:72:12)
    at Object.toggle (/packages/atom-p5js/lib/atom-p5js.js:63:14)
    at HTMLElement.atomP5jsToggle (/packages/atom-p5js/lib/atom-p5js.js:34:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347765)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725694)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733617)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
  2x -2:52 atom-p5js:toggle (a.)
     -2:21.1.0 core:cut (div.package-readme.native-key-bindings)
     -2:20.3.0 application:new-file (div.package-readme.native-key-bindings)
  3x -2:18.9.0 core:backspace (input.hidden-input)
     -2:18.2.0 application:new-file (input.hidden-input)
```

### Non-Core Packages

```
atom-p5js 0.1.1 
compare-files 0.8.1 
script 3.18.1 
split-diff 1.6.1 
tabs-to-spaces 1.0.5 
```

**Comment by ndr-brt** [comment]
When you lauched the command, there was at least one opened file?
This plugin works only if launched on a p5js script file (similar to the examples files: https://github.com/ndr-brt/atom-p5js/tree/master/examples)
